config/routes.rb
Rails.application.routes.draw do
  root 'publics#index'


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get 'carts/empty_all', to: 'carts#delete_all', as: 'delete_cart'
  resources :carts

  # get '/', to: 'categories#search', as: 'search'
  resources :categories
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    belongs_to :product
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :authenticate_user!
    before_action :user_access
    before_action :user_cart

  def index
    
    @carts = @user.carts.all

  end


  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      flash[:notice] = 'Product added to Cart successfully'
      redirect_to(:controller => 'publics', :action => 'index')
    else
      redirect_to root_path
    end
    
  end

  def destroy
    @cart = Cart.find(params[:id]).destroy
    flash[:notice] = 'Product deleted from cart'
    redirect_to(:action => 'index',:user_id => current_user.id)
  end

  def delete_all
    
    @carts = Cart.where(:user_id => current_user.id).destroy_all
    flash[:notice] = 'Cart Destroyed successfully'
    redirect_to(:action => 'index',:user_id => current_user.id)

  end


  private
  def user_access
    if current_user.role_id == 1
        redirect_to root_path
    end
  end

  def cart_params
    params.permit(:user_id, :product_id, :category_id)
  end

  

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<div class="form-group col-3">

    <%= f.hidden_field :product_id, :value=> params[:product_id], class:'form-control' %>
</div>
<div class="form-group col-3">

    <%= f.hidden_field :category_id, :value=> params[:category_id], class:'form-control' %>
</div>
<div class="form-group col-3 mb-2">

    <%= f.hidden_field :user_id, :value=> params[:user_id], class:'form-control' %>
</div>

app/views/carts/index.html.erb
<%= link_to 'Back' , root_path, class:'btn btn-light' %>


    <h1>Cart</h1>
    <%= link_to 'Empty Cart', delete_cart_path(:user_id => current_user.id), class:'btn-sm btn btn-danger' %>
        <table class="table">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Product</th>
                    <th>Category ID</th>
                    <th>Buyer</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                <% @carts.each do |cart| %>
                    <tr>
                        <td>
                            <%= cart.id %>
                        </td>
                        <td>
                          <%= cart.product.name %>
                        </td>
                        <td>
                          <%= cart.product.category.name %>
                        </td>
                        <td>
                            <%= cart.user.email %>
                        </td>
                        <td class="d-flex gap-1">
                        <%= button_to 'Destroy' , cart, method: :delete, data: {
                        confirm: 'Are you sure?' }, class:'btn-sm btn btn-danger' %>
                        </td>
                    </tr>
                    <% end %>
            </tbody>
        </table>

        <br>

app/views/carts/new.html.erb
    <!-- <span>< % = @cart.product.category.name %>/< % =  @cart.product.name %>/<span> -->

<%= form_with model: @cart, url: {:controller=> 'carts', :action=> 'create'}, method: :post, local:
    true do
    |f| %>
    
    <%= render(:partial => 'form', :locals=>{:f => f}) %>
    <div class="card col-4">
        <h1 class="card card-header col-12">Cart</h1>
        <div class="card-body">
            <p class="card-text">Confirm Your Cart!!!</p>
        </div>
            <div class="form-group mb-3 card-footer">
                <%= submit_tag 'Confirm' , class:'btn btn-primary' %>
                <%= link_to "Cancel", root_path, :class => 'btn btn-secondary' %>
                <% end %>
            </div>
    </div>
   