config/routes.rb
Rails.application.routes.draw do
  root 'publics#index'


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get 'carts/empty_all', to: 'carts#delete_all', as: 'delete_cart'
  resources :carts

  # get '/', to: 'categories#search', as: 'search'
  resources :categories
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :products
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :admin_access, except: [:show]
  before_action :authenticate_user!, except: [:show]
  before_action :cart_count
  

  
  def index
    @categories = Category.all
  end

  def show
    @categories = Category.all
    if params[:search].present?
      @products =  Category.find(params[:id]).products.where('name ILIKE ?', "%#{params[:search]}%")
    else
        @category = Category.find(params[:id])
    end
  end

  # def search 
  #   if params[:search].present?
  #       @category = Category.find(params[:id])
  #       @products =  @category.products.where('name ILIKE ?', "%#{params[:search]}%")
  #   end
  #     render 'show'
  # end

  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to(:action => 'index')
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(params_category)
      flash[:notice] = 'Category Updated successfully.'
      redirect_to(:action => 'index')
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    flash[:notice] = 'Category Deleted Successfully'
    redirect_to(:action => 'index')
  end

  private
  def params_category
    params.require(:category).permit(:name)
  end

  # def find_category
  #   if params[:category_id]
  #     @category = Category.find(params[:category_id])
  #   end
  # end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <div class="mb-3">
    <%= f.label(:name) %>
      <%= f.text_field :name, class: "form-control" %>
  </div>

  <!-- < % = f.hidden_field :user_id, value: current_admin_user.id , class: "form-control" if current_admin_user %> -->

app/views/categories/edit.html.erb
<h1 class="mt-5">Edit Category</h1>

<div class="col-md-6">
    <%= form_with model: @category, url: category_path(@category), method: :patch, local: true do |f| %>
        
        <%= render(:partial=> 'form', :locals => {:f => f}) %>
        <div class="form-group mb-3">
            <%= submit_tag 'Update' , class:'btn btn-primary' %>
        </div>    
    <% end %>
</div>
<%= link_to 'Back' , categories_path %>

app/views/categories/index.html.erb
<%= link_to 'Back' , root_path, class:'btn btn-light' %>


<h1>Categories</h1>
<%= link_to 'New Categories' , new_category_path, class:'btn btn-secondary' %>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>

        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <td>
                        <%= category.name %>
                    </td>
                    <td class="d-flex gap-1">
                    <%= link_to 'Show Products' , category, class:'btn-sm btn btn-warning' %>
                    <%= link_to 'Create Products', products_path(:category_id => category.id), class:'btn-sm btn btn-warning' %>
                    <%= link_to 'Edit', edit_category_path(category),class:'btn-sm btn btn-primary' %>
                    <%= button_to 'Destroy', category, method: :delete, data: { turbo_confirm: 'Are you sure?'}, class:'btn-sm btn btn-danger' %>
                </td>
                </tr>
                <% end %>
        </tbody>
    </table>

    <br>

app/views/categories/new.html.erb
<h1 class="mt-5">New Category</h1>


<div class="col-md-5">
    <%= form_with model: @category, url: {:action=> 'create'}, method: :post, local: true do |f| %>

        <%= render(:partial=>'form' , :locals=>{:f => f}) %>
            <div class="form-group mb-3">
                <%= submit_tag 'Create' , class:'btn btn-primary' %>
            </div>
            <% end %>
</div>
<%= link_to 'Back' , categories_path %>

app/views/categories/show.html.erb
<div>
<%= link_to 'Back' , :back, class:'btn btn-light mb-3' %>

<div class="float-end mt-1">
    <%= form_with model: @public, :action=> category_path, method: :get do |f| %>
        <span>
            <%= link_to('X', :back, class:'text-decoration-none text-dark') if !params[:search].blank? %>
        </span>
        <%= f.text_field :search, :autocomplete=>"off", class:"" %>
            <%= submit_tag 'Search' ,class:"btn btn-outline-success" %>
                <% end %>
</div>

</div>
<h1>
    <%= @category.name if !@category.blank?%>
</h1>

<div class="row mt-5">
    <% if !@category.blank? %>
    <% @category.products.each do |product| %>
        <div class="card col-md-3 me-auto mb-4" style="width: 18rem;">
            <%= image_tag product.image, :size=> "500x250", class:'card-img-top' %>
                <div class="card-body">
                    <h5 class="card-title">Title <%= product.name %>
                    </h5>
                    <p class="card-text"><b>PRICE </b>
                        <%= product.price %>$
                    </p>
                </div>
                <div class="card-body">
                    <%= link_to 'View Product' , product, class:'card-link pe-auto' %>

                </div>
        </div>
        <% end %>
        <% end %>

    <% if @category.blank? %>
    <p>
        <%= 'No Record Found' if @products.empty? %>
    </p>
    <% @products.each do |product| %>
        <div class="card col-md-3 me-auto mb-4" style="width: 18rem;">
            <%= image_tag product.image, :size=> "500x250", class:'card-img-top' %>
                <div class="card-body">
                    <h5 class="card-title">Title <%= product.name %>
                    </h5>
                    <p class="card-text"><b>PRICE </b>
                        <%= product.price %>$
                    </p>
                </div>
                <div class="card-body">
                    <%= link_to 'View Product' , product, class:'card-link pe-auto' %>
                </div>
        </div>
    <% end %>
    <% end %>

</div>