config/routes.rb
Rails.application.routes.draw do
  root 'publics#index'


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get 'carts/empty_all', to: 'carts#delete_all', as: 'delete_cart'
  resources :carts

  # get '/', to: 'categories#search', as: 'search'
  resources :categories
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

    include ProductValidatable
    include ImageResize
    
    has_one_attached :image
    belongs_to :category
    has_many :carts

    # scope :search, lambda{ |query| where(['name LIKE ?', '%' + query +'%'])}




end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :admin_access, except: [:show]
  before_action :find_category
  before_action :cart_count

  def index
    @products = @category.products.all
  end

  def show
    
    # @categories = Category.all
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new(:category_id => @category.id)

  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product Created Successfully'
      redirect_to(:action => 'index', :category_id => @category.id)
    else
      render(:action => 'new')
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product Updated Successfully'
      redirect_to(:action => 'index', :category_id => @category.id)
    else
      render('edit')
    end
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    flash[:notice] = 'Product Deleted Successfully'
    redirect_to(:action => 'index', :category_id => @category.id)
  end

  private
    
    def product_params
      params.require(:product).permit(:name, :price, :image, :category_id)
    end

    def find_category
      if params[:category_id]
        @category = Category.find(params[:category_id])
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <div class="mb-3">
    <%= f.label(:name) %>
      <%= f.text_field :name, class: "form-control" %>
      <% if @product.errors.any? %>
        <% @product.errors.full_messages_for(:name).each do |error| %>
          <span>
            <li class="text-danger">
              <%= error %>
            </li>
          </span>
          <% end %>
            <% end %>
  </div>
  <div class="mb-3">
    <%= f.label(:price) %>
      <%= f.text_field :price, class: "form-control" %>
      <% if @product.errors.any? %>
        <% @product.errors.full_messages_for(:price).each do |error| %>
          <span>
            <li class="text-danger">
              <%= error %>
            </li>
          </span>
          <% end %>
            <% end %>
  </div>

<div>
  <%= f.hidden_field :category_id %>
</div>

  <div class="mb-3">
    <%= f.label(:image) %>
      <%= f.file_field :image, class: "form-control" %>
      <% if @product.errors.any? %>
        <% @product.errors.full_messages_for(:image).each do |error| %>
          <span>
            <li class="text-danger">
              <%= error %>
            </li>
          </span>
          <% end %>
            <% end %>
  </div>
 

app/views/products/edit.html.erb
<%= link_to 'Back' , :back, class:'btn btn-light' %>

<h1>Editing Product</h1>
<%= form_with model: @product, url: product_path(@product, :category_id => @category.id), method: :patch, local: true do |f| %>

<%= render(:partial=>'form' , :locals=>{:f => f}) %>

    <div class="form-group mb-3">
        <%= submit_tag 'Update' , class:'btn btn-primary' %>
    </div>
    <% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= link_to 'Back', categories_path, class:'btn btn-light' %>

<h1>Products</h1>
<%= link_to 'New Product' , new_product_path(:category_id => @category.id), class:'btn btn-secondary' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Category</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td> 
          <%= product.price %>$
        </td>
        <td>
          <%= image_tag product.image_as_thumbnails %>
        </td>
        <td>
          <%= product.category.name %>
        </td>
        <td class="d-flex gap-1"><%= link_to 'Edit', edit_product_path(product, :category_id => @category.id), class:'btn btn-info btn-sm' %>
        <%= button_to 'Destroy' , {:action => 'destroy', :id => product.id, :category_id => @category.id}, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:'btn-sm btn btn-danger'%>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<%= link_to 'Back' , :back, class:'btn btn-light' %>


<h1>New Product</h1>

<div class="col-md-6">
    <%= form_with model: @product, url: {:action=> 'create', :category_id => @category.id}, method: :post, local: true do |f| %>
       
        <%= render(:partial=>'form' , :locals=>{:f => f}) %>
         
        <div class="form-group mb-3">
            <%= submit_tag 'Create' , class:'btn btn-primary' %>
        </div>
    <% end %>
</div>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= link_to 'Back' , :back, class:'btn btn-light mb-5' %>

    <!-- <span>< % = @product.category.name %>/<span> -->
        
    <div class="container d-flex gap-5">
        <div class="card col-md-3 me-auto mb-4" style="width: 25rem;">
            <%= image_tag @product.image, :size=> "400x400", class:'card-img-top' %>
        </div>
        <div class="card-body">
            <h5 class="card-title mt-3">Title <%= @product.name %>
            </h5>
            <p class="card-text mt-5"><b>PRICE </b>
                <%= @product.price %>
            </p>
            <p class="card-text mt-2"><b>CATEGORY </b>
                <%= @product.category.name %>
            </p>
            <% if user_signed_in? %>
                <% if current_user.role_id==2 %>

                <%= link_to 'Add to Cart', new_cart_path(:product_id => @product.id, :user_id => current_user.id, :category_id => @product.category.id) %>
                <% end %>
            <% end %>
        </div>
    </div>