config/routes.rb
Rails.application.routes.draw do
  root 'publics#index'


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  get 'carts/empty_all', to: 'carts#delete_all', as: 'delete_cart'
  resources :carts

  # get '/', to: 'categories#search', as: 'search'
  resources :categories
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    belongs_to :product
    
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :products
    
end

app/models/concerns/image_resize.rb
module ImageResize

    extend ActiveSupport::Concern

    included do

        def image_as_thumbnails
            image.variant(resize_to_limit: [100, 50]).processed
        end

        def image_as_card
            image.variant(resize_to_limit: [300, 300]).processed
        end
    end

end

app/models/concerns/user_validation.rb
module UserValidation


extend ActiveSupport::Concern

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  included do

    validates :email, :presence => true,
              :length => { :maximum => 40},
              :format => VALID_EMAIL_REGEX,
              :confirmation => true,
              :uniqueness => true
    validates :password, :presence => true

    validates :username, :presence => true

    end
end

app/models/product.rb
class Product < ApplicationRecord

    include ProductValidatable
    include ImageResize
    
    has_one_attached :image
    belongs_to :category
    has_many :carts

    # scope :search, lambda{ |query| where(['name LIKE ?', '%' + query +'%'])}




end

app/models/role.rb
class Role < ApplicationRecord

belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  
  include UserValidation

  has_one :role
  has_many :carts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable,
         :trackable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
    end

    def after_sign_in_path_for(resource)
      if current_user.role_id == 1
        categories_path
      else
        root_path
      end
    end

    def admin_access
      if current_user.role_id == 2
          flash[:error] = "You are not allowed to have access to this page."
        redirect_to root_path
      end
    end

    def user_cart
      if user_signed_in?
          if params[:user_id]
          @user = User.find(params[:user_id])
          end
      end
    end

    def cart_count
      if user_signed_in?
        @user = User.find(current_user.id)
      end
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :authenticate_user!
    before_action :user_access
    before_action :user_cart

  def index
    
    @carts = @user.carts.all

  end


  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      flash[:notice] = 'Product added to Cart successfully'
      redirect_to(:controller => 'publics', :action => 'index')
    else
      redirect_to root_path
    end
    
  end

  def destroy
    @cart = Cart.find(params[:id]).destroy
    flash[:notice] = 'Product deleted from cart'
    redirect_to(:action => 'index',:user_id => current_user.id)
  end

  def delete_all
    
    @carts = Cart.where(:user_id => current_user.id).destroy_all
    flash[:notice] = 'Cart Destroyed successfully'
    redirect_to(:action => 'index',:user_id => current_user.id)

  end


  private
  def user_access
    if current_user.role_id == 1
        redirect_to root_path
    end
  end

  def cart_params
    params.permit(:user_id, :product_id, :category_id)
  end

  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :admin_access, except: [:show]
  before_action :authenticate_user!, except: [:show]
  before_action :cart_count
  

  
  def index
    @categories = Category.all
  end

  def show
    @categories = Category.all
    if params[:search].present?
      @products =  Category.find(params[:id]).products.where('name ILIKE ?', "%#{params[:search]}%")
    else
        @category = Category.find(params[:id])
    end
  end

  # def search 
  #   if params[:search].present?
  #       @category = Category.find(params[:id])
  #       @products =  @category.products.where('name ILIKE ?', "%#{params[:search]}%")
  #   end
  #     render 'show'
  # end

  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to(:action => 'index')
    else
      render :action => 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(params_category)
      flash[:notice] = 'Category Updated successfully.'
      redirect_to(:action => 'index')
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    flash[:notice] = 'Category Deleted Successfully'
    redirect_to(:action => 'index')
  end

  private
  def params_category
    params.require(:category).permit(:name)
  end

  # def find_category
  #   if params[:category_id]
  #     @category = Category.find(params[:category_id])
  #   end
  # end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :admin_access, except: [:show]
  before_action :find_category
  before_action :cart_count

  def index
    @products = @category.products.all
  end

  def show
    
    # @categories = Category.all
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new(:category_id => @category.id)

  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product Created Successfully'
      redirect_to(:action => 'index', :category_id => @category.id)
    else
      render(:action => 'new')
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product Updated Successfully'
      redirect_to(:action => 'index', :category_id => @category.id)
    else
      render('edit')
    end
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    flash[:notice] = 'Product Deleted Successfully'
    redirect_to(:action => 'index', :category_id => @category.id)
  end

  private
    
    def product_params
      params.require(:product).permit(:name, :price, :image, :category_id)
    end

    def find_category
      if params[:category_id]
        @category = Category.find(params[:category_id])
      end
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
   
  before_action :user_cart
  before_action :cart_count

    def index
      @categories = Category.includes(:name)

        if   user_signed_in?
            @carts = @user.carts.includes(:user_id)
        end
        if params[:search].present?
            @products =  Product.joins(:category).where('categories.name ILIKE ? or products.name ILIKE ?', "%#{params[:search]}%" , "%#{params[:search]}%")
        else
            @products = Product.all.includes(image_attachment: :blob)
        end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <%= link_to 'E-Commerce' , root_path, class:'navbar-brand' %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu">
                            <% Category.all.each do |category|  %>
                                <li class="dropdown-item">
                                    <%= link_to category.name, category, class:'text-decoration-none text-dark' %> 
                                </li>
                            <% end %>
                        </ul>
                    </li>
                    <% if user_signed_in? %>
                        <li class="nav-item text-light d-flex">
                            <%= link_to '' , carts_path(:user_id=> current_user.id), class:'fa fa-shopping-cart nav-link
                                active' if current_user.role_id==2 %>
                                <span>
                                    <%= @user.carts.count if current_user.role_id==2 %>
                                </span>
                        </li>
                        <li class="nav-item">
                            <%= link_to 'Admin' , categories_path, class:'nav-link active' if current_user.role_id==1 %>
                        </li>
                        <% end %>
                </ul>
                <div class="btn-group">
                    <button class="btn btn-light dropdown-toggle me-1" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <%= current_user.username if user_signed_in? %>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li>
                            <%= link_to 'Sign In' , new_user_session_path, class:"dropdown-item" if !user_signed_in? %>
                        </li>
                        <li>
                            <%= link_to 'Sign Up' , new_user_registration_path, class:"dropdown-item" if
                                !user_signed_in? %>
                        </li>
                        <li>
                            <%= link_to 'Edit Profile' , edit_user_registration_path,class:"dropdown-item" if user_signed_in? %>
                        </li>
                        <li>
                            <%= button_to 'Logout' , destroy_user_session_path, method: :delete,class:"dropdown-item" if
                                user_signed_in? %>
                        </li>
                    </ul>
                </div>

            </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Com</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>

  </head>
  <body>


    <%= render(:partial => 'layouts/navbar') %>
    <div class="container">

          <% if !flash[:notice].blank? %>
            <div class="alert alert-success">
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              <%= flash[:notice] %>
            </div>
            <% end %>
              <% if !flash[:error].blank? %>
                <div class="alert alert-warning">
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  <%= flash[:error] %>
                </div>
                <% end %>
                  
      <%= yield %>
    </div>
  </body>
</html>